### PR TITLE
Ticking issue in IE - in response to #8

### PR DESCRIPTION
**Pull request by fitzy90**
This seems to correct the IE ticking issue #8.
If its OK to commit that would be great

### CODE REVIEW

**Comment by simonbrunel** [comment]
Thanks @fitzy90, however this change silents the issue instead of fixing it, which can potentially hide real errors later. We need to figure out why `stub` is undefined (or null) in some cases, maybe `event.target` is not correct or maybe IE doesn't accept expando?

I'm not able to reproduce this issue in IE11, what version are you using to reproduce this error? can you log the content of `event` and `node` when `stub` is undefined?

**Comment by fitzy90** [comment]
Hey

I have managed to replicate for you, see the test case link. I haven’t looked at it for very long so I can’t really comment.

If you use IE11 to navigate here you should see the issue in the developer tools

http://chart.tech-solutions.co.uk/

Let me know if can help any further

Thanks

Jack

**Comment by simonbrunel** [comment]
Thanks @fitzy90, I can reproduce it! I think the problem is that the scroll event is not correctly removed ([at this line](https://github.com/chartjs/chartjs-plugin-deferred/blob/master/src/plugin.js#L120)), certainly because `Chart.helpers.removeEvent` doesn't call the associated "remove" method matching the call at [line 104](https://github.com/chartjs/chartjs-plugin-deferred/blob/master/src/plugin.js#L104)

**Comment by simonbrunel** [comment]
@fitzy90 I pushed a fix for this issue in master (ee8c7a9ee18558304ed9d065f8354db709b964c9), can you confirm that it works correctly now?

**Comment by fitzy90** [comment]
@simonbrunel I can confirm that works perfectly! Thanks for your help on this!

**Comment by simonbrunel** [comment]
Thanks @fitzy90, I'm closing this PR and will release the fix very soon.

**Pull request closed without merging**
